import { db } from '../db';
import { buyerPersonas } from '@shared/schema';

export const PERSONA_SEED_DATA = [
  {
    code: 'BP-OWNER',
    name: 'The Owner/Developer',
    icon: 'Building2',
    roleTitle: 'Portfolio Stakeholder / Economic Buyer',
    roleVariants: ['Real Estate Developer', 'Property Owner', 'Investment Manager', 'Asset Manager', 'Managing Partner', 'Principal'],
    organizationType: 'Real Estate Development/Investment',
    description: 'Decision-maker focused on ROI, asset value, and risk mitigation. Values standardized portfolio data to prevent repeat mistakes.',
    coreValues: ['ROI', 'Asset Value', 'Scaling', 'Risk Mitigation'],
    primaryPain: 'Fragmented data across a large portfolio leading to repeat mistakes and lost capital',
    secondaryPain: 'Lack of accurate documentation for financing and insurance purposes',
    hiddenFear: 'Discovering hidden structural issues after acquisition that destroy deal economics',
    purchaseTriggers: ['Property acquisition', 'Portfolio renovation planning', 'Insurance documentation needs', 'Capital improvement budgeting'],
    valueDriver: 'Standardize portfolio data to compound value',
    valueHook: 'Standardize your portfolio data to ensure every project compounds value instead of creating chaos.',
    exactLanguage: ['Asset ROI', 'portfolio standardization', 'capital efficiency', 'risk reduction', 'value compounding'],
    avoidWords: ['Point Cloud density', 'BIM complexity', 'technical specifications', 'modeling details', 'LOD levels'],
    decisionCriteria: ['Speed of delivery', 'Cost certainty', 'Documentation quality', 'Insurance/financing compliance'],
    dealbreakers: ['Missed deadlines', 'Unclear pricing', 'No references from similar projects'],
    projectPhases: ['Pre-acquisition', 'Due diligence', 'Capital planning', 'Renovation kickoff'],
    budgetAuthority: 'Full authority',
    typicalBudgetRange: '$15,000 - $100,000+',
    influenceChain: { reportsTo: 'Board/Investors', needsApprovalFrom: [], influencedBy: ['Legal counsel', 'Asset managers'] },
    tonePreference: 'Executive summary style—bottom line first',
    communicationStyle: 'Direct and concise',
    attentionSpan: 'Short—lead with value',
    technicalTriggers: ['Accuracy guarantees', 'Delivery speed', 'Documentation completeness'],
    emotionalTriggers: ['Peace of mind', 'Confidence in decisions', 'Competitive advantage'],
    vetoPower: true,
    defaultRiskLevel: 'low',
    disqualifiers: ['No budget approval process', 'Just researching'],
    buyingModeStrategies: {
      firefighter: 'Lead with speed: "We can have verified documentation in your hands within 5 business days to meet your deadline."',
      optimizer: 'Lead with ROI: "Our clients typically see 3x return through reduced change orders and faster permit approval."',
      innovator: 'Lead with competitive edge: "Be the first in your market to leverage digital twin technology for asset management."'
    },
    requiredAssets: ['executive_summary', 'roi_calculator', 'case_study_similar_asset'],
    proposalSections: ['executive_summary', 'timeline', 'investment', 'risk_mitigation'],
  },
  {
    code: 'BP-ARCH',
    name: 'The Architect',
    icon: 'Compass',
    roleTitle: 'Design Lead / Project Architect',
    roleVariants: ['Principal Architect', 'Design Director', 'Project Architect', 'Senior Designer', 'Design Lead'],
    organizationType: 'Architecture Firm',
    description: 'Design professional who values design excellence, precision, and client trust. Needs reliable base data to protect design vision and billable hours.',
    coreValues: ['Design Excellence', 'Precision', 'Client Trust', 'Professional Reputation'],
    primaryPain: 'Wasted billable hours and design compromises caused by starting projects with inaccurate as-built drawings',
    secondaryPain: 'Too much time spent on documentation instead of design',
    hiddenFear: 'Design decisions based on inaccurate data reflecting poorly on professional reputation',
    purchaseTriggers: ['Renovation project kickoff', 'Historic preservation', 'Complex adaptive reuse', 'Existing building analysis'],
    valueDriver: 'Design-ready models you can trust',
    valueHook: 'Stop burning billable hours on manual measuring. We deliver design-ready models you can trust.',
    exactLanguage: ['Revit-ready accuracy', 'design integrity', 'accurate base drawings', 'design time savings', 'as-built verification'],
    avoidWords: ['Cost savings', 'cheap', 'budget-friendly', 'good enough', 'rough estimate', 'ballpark'],
    decisionCriteria: ['Accuracy', 'Compatibility with design software', 'Turnaround time', 'Technical expertise'],
    dealbreakers: ['Low accuracy tolerance', 'Incompatible file formats', 'Poor communication'],
    projectPhases: ['Schematic design', 'Design development', 'Construction documents'],
    budgetAuthority: 'Recommender—often needs partner/owner approval',
    typicalBudgetRange: '$5,000 - $40,000',
    influenceChain: { reportsTo: 'Managing Principal', needsApprovalFrom: ['Principal', 'Client (for passthrough)'], influencedBy: ['Consultants', 'Project managers'] },
    tonePreference: 'Technical but respectful of design sensibility',
    communicationStyle: 'Visual and detail-oriented',
    attentionSpan: 'Medium—appreciates thoroughness',
    technicalTriggers: ['Revit-ready deliverables', 'LOD specifications', 'Accuracy tolerances'],
    emotionalTriggers: ['Design confidence', 'Time for creativity', 'Professional credibility'],
    vetoPower: true,
    defaultRiskLevel: 'medium',
    disqualifiers: ['Low budget expectations', 'Unrealistic timelines'],
    buyingModeStrategies: {
      firefighter: 'Lead with rescue: "We specialize in tight turnarounds—get Revit-ready deliverables before your design deadline."',
      optimizer: 'Lead with efficiency: "Eliminate field verification trips and reduce documentation time by 40%."',
      innovator: 'Lead with technology: "Leverage point cloud data for design exploration possibilities not visible in 2D."'
    },
    requiredAssets: ['sample_deliverables', 'accuracy_specifications', 'revit_workflow_guide'],
    proposalSections: ['scope_technical', 'deliverables', 'accuracy_methodology', 'timeline'],
  },
  {
    code: 'BP-ENG',
    name: 'The Engineer',
    icon: 'Calculator',
    roleTitle: 'Lead Engineer / Technical Director',
    roleVariants: ['MEP Engineer', 'Structural Engineer', 'Civil Engineer', 'Engineering Project Manager', 'Technical Director', 'Lead Engineer'],
    organizationType: 'Engineering Firm',
    description: 'Technical professional requiring precise measurements for system design and coordination. Values accuracy, safety, and data integrity above all.',
    coreValues: ['Accuracy', 'Safety', 'Compliance', 'Data Integrity'],
    primaryPain: 'High-risk field surprises or code failures caused by incomplete or guessed existing-condition data',
    secondaryPain: 'Excessive site visits to verify conditions',
    hiddenFear: 'Engineering calculations based on wrong measurements causing liability issues',
    purchaseTriggers: ['MEP retrofit', 'Structural analysis', 'System upgrades', 'Coordination requirements'],
    valueDriver: 'Remove technical uncertainty from designs',
    valueHook: 'Tolerance-verified models that remove technical uncertainty so your designs pass review without drama.',
    exactLanguage: ['tolerance specifications', 'tolerance-verified', 'clash-free coordination', 'MEP accuracy', 'structural verification'],
    avoidWords: ['approximate', 'estimate', 'close enough', 'typical', 'ballpark'],
    decisionCriteria: ['Measurement accuracy', 'MEP capture detail', 'Structural documentation', 'Data format compatibility'],
    dealbreakers: ['Accuracy below 1/4"', 'Missing system components', 'Incomplete deliverables'],
    projectPhases: ['System analysis', 'Detailed design', 'Coordination', 'Construction administration'],
    budgetAuthority: 'Project-level authority, larger needs approval',
    typicalBudgetRange: '$8,000 - $50,000',
    influenceChain: { reportsTo: 'Principal Engineer', needsApprovalFrom: ['Department head', 'Client for large projects'], influencedBy: ['Other disciplines', 'BIM coordinators'] },
    tonePreference: 'Highly technical—specifics matter',
    communicationStyle: 'Data-driven and systematic',
    attentionSpan: 'Long—wants all technical details',
    technicalTriggers: ['Accuracy certifications', 'QA/QC processes', 'Multi-discipline coordination'],
    emotionalTriggers: ['Professional confidence', 'Liability protection', 'Efficiency gains'],
    vetoPower: true,
    defaultRiskLevel: 'high',
    disqualifiers: ['Low accuracy requirements', 'Unwilling to invest in quality'],
    buyingModeStrategies: {
      firefighter: 'Lead with reliability: "Critical path scanning with guaranteed accuracy—we don\'t cut corners under pressure."',
      optimizer: 'Lead with precision ROI: "Reduce RFIs by 60% with verified coordination data."',
      innovator: 'Lead with capability: "Capture hidden systems and conditions traditional surveys miss."'
    },
    requiredAssets: ['technical_specifications', 'accuracy_certification', 'qa_qc_process_doc'],
    proposalSections: ['technical_methodology', 'accuracy_specs', 'mep_scope', 'qa_qc'],
  },
  {
    code: 'BP-PM',
    name: 'The Project Manager / CM',
    icon: 'HardHat',
    roleTitle: 'Construction Lead / Field Operations',
    roleVariants: ['Project Executive', 'Senior PM', 'Preconstruction Manager', 'VDC Manager', 'Construction Manager', 'Field Operations Lead'],
    organizationType: 'General Contractor / CM Firm',
    description: 'Construction professional focused on efficiency, accountability, and schedule adherence. Values practical, field-ready documentation that prevents RFIs and re-work.',
    coreValues: ['Efficiency', 'Accountability', 'Schedule Adherence', 'Profit Margin Protection'],
    primaryPain: 'Constant RFIs, re-work, and "blame loops" between trades due to coordination breakdowns',
    secondaryPain: 'Coordination conflicts between trades',
    hiddenFear: 'Margin erosion from unforeseen conditions',
    purchaseTriggers: ['Preconstruction planning', 'Value engineering', 'Risk assessment', 'Coordination kickoff'],
    valueDriver: 'Eliminate coordination risk and schedule slips',
    valueHook: 'Eliminate coordination risk and schedule slips with clash-checked, field-verified data.',
    exactLanguage: ['change order prevention', 'margin protection', 'schedule certainty', 'trade coordination', 'clash-checked'],
    avoidWords: ['theoretical', 'design intent', 'approximate', 'conceptual'],
    decisionCriteria: ['Turnaround speed', 'Cost value', 'Field-ready format', 'Coordination utility'],
    dealbreakers: ['Delayed delivery', 'Unusable formats', 'Missing critical areas'],
    projectPhases: ['Preconstruction', 'Buyout', 'Mobilization', 'Construction'],
    budgetAuthority: 'Full authority on ops budget, large needs exec approval',
    typicalBudgetRange: '$10,000 - $75,000',
    influenceChain: { reportsTo: 'Division Manager / Owner', needsApprovalFrom: ['Operations', 'Client for passthrough'], influencedBy: ['VDC team', 'Superintendents'] },
    tonePreference: 'Direct, practical, bottom-line focused',
    communicationStyle: 'Action-oriented',
    attentionSpan: 'Short—get to the point',
    technicalTriggers: ['Coordination-ready models', 'Field-verified data', 'Quick turnaround'],
    emotionalTriggers: ['Margin protection', 'Schedule confidence', 'Risk reduction'],
    vetoPower: true,
    defaultRiskLevel: 'medium',
    disqualifiers: ['Design-only projects', 'Theoretical exercises'],
    buyingModeStrategies: {
      firefighter: 'Lead with speed: "Emergency scanning support—mobilize in 24 hours, deliver in 5 days."',
      optimizer: 'Lead with value: "Investment pays for itself in first avoided change order."',
      innovator: 'Lead with competitive edge: "Win more bids with verified existing condition data in your proposals."'
    },
    requiredAssets: ['roi_case_study', 'turnaround_guarantee', 'coordination_workflow'],
    proposalSections: ['executive_summary', 'timeline', 'coordination_value', 'investment'],
  },
  {
    code: 'BP-FAC',
    name: 'The Facilities Manager',
    icon: 'KeyRound',
    roleTitle: 'Operations Director / Building Manager',
    roleVariants: ['Property Manager', 'Facility Manager', 'Building Operations Manager', 'Operations Director', 'Building Manager'],
    organizationType: 'Property Management / Corporate Real Estate',
    description: 'Operations professional managing building performance and tenant improvements. Values uptime, maintenance efficiency, and lifecycle value.',
    coreValues: ['Uptime', 'Maintenance Efficiency', 'Lifecycle Value', 'Budget Control'],
    primaryPain: 'Reactive maintenance and poor documentation making it impossible to manage assets effectively',
    secondaryPain: 'Tenant improvement projects complicated by unknown conditions',
    hiddenFear: 'System failures due to undocumented modifications',
    purchaseTriggers: ['Tenant improvement wave', 'System replacement planning', 'Insurance documentation', 'Energy audits'],
    valueDriver: 'Transform maintenance from reactive to predictive',
    valueHook: 'The last survey you\'ll ever need—usable asset data that turns maintenance from reactive to predictive.',
    exactLanguage: ['operational documentation', 'predictive maintenance', 'asset data', 'lifecycle management', 'system mapping'],
    avoidWords: ['construction complexity', 'design development', 'architectural', 'design intent'],
    decisionCriteria: ['Documentation completeness', 'FM software compatibility', 'Cost effectiveness', 'Minimal disruption'],
    dealbreakers: ['Excessive building disruption', 'Incomplete coverage', 'Non-FM formats'],
    projectPhases: ['Capital planning', 'TI project initiation', 'System replacement', 'Documentation updates'],
    budgetAuthority: 'Project budget authority, capex needs approval',
    typicalBudgetRange: '$5,000 - $30,000',
    influenceChain: { reportsTo: 'Director of Operations', needsApprovalFrom: ['Owner/Asset Manager'], influencedBy: ['Engineering team', 'Tenants'] },
    tonePreference: 'Practical and operationally focused',
    communicationStyle: 'Solution-oriented',
    attentionSpan: 'Medium—values efficiency',
    technicalTriggers: ['FM integration', 'System documentation', 'Minimal disruption scanning'],
    emotionalTriggers: ['Operational control', 'Problem prevention', 'Professional competence'],
    vetoPower: false,
    defaultRiskLevel: 'low',
    disqualifiers: ['New construction', 'Design-focused projects'],
    buyingModeStrategies: {
      firefighter: 'Lead with solution: "Emergency documentation for insurance claims or system failures—48 hour response."',
      optimizer: 'Lead with efficiency: "Reduce vendor coordination time and improve maintenance planning."',
      innovator: 'Lead with digital transformation: "Create a digital twin for predictive maintenance and energy optimization."'
    },
    requiredAssets: ['fm_integration_guide', 'operational_case_study', 'minimal_disruption_methodology'],
    proposalSections: ['operational_value', 'methodology', 'timeline', 'integration'],
  },
  {
    code: 'BP-PROC',
    name: 'The Procurement Leader',
    icon: 'Users',
    roleTitle: 'Vendor Manager / Purchasing Lead',
    roleVariants: ['Procurement Manager', 'Sourcing Lead', 'Vendor Manager', 'Purchasing Director', 'Supply Chain Manager'],
    organizationType: 'Enterprise / Large Organization',
    description: 'Procurement professional focused on reliability, predictability, and contract compliance. Values vendor accountability and scope certainty.',
    coreValues: ['Reliability', 'Predictability', 'Contract Compliance', 'Budget Control'],
    primaryPain: 'Unreliable vendors and scope creep that lead to budget overruns and administrative headaches',
    secondaryPain: 'Managing multiple vendors with inconsistent quality',
    hiddenFear: 'Vendor failure causing project delays and budget blame',
    purchaseTriggers: ['Vendor consolidation', 'New project requirements', 'Quality issues with current vendors', 'Cost reduction initiatives'],
    valueDriver: 'One accountable partner for all spatial data needs',
    valueHook: 'Guaranteed turnaround and zero scope creep—one accountable partner for all your spatial data needs.',
    exactLanguage: ['guaranteed turnaround', 'scope certainty', 'contract compliance', 'accountable partner', 'fixed pricing'],
    avoidWords: ['variable scope', 'estimate', 'approximate', 'depending on conditions'],
    decisionCriteria: ['Price predictability', 'Delivery guarantees', 'Vendor track record', 'Contract flexibility'],
    dealbreakers: ['Unclear pricing', 'No SLA', 'Poor references'],
    projectPhases: ['Vendor selection', 'Contract negotiation', 'Ongoing management'],
    budgetAuthority: 'Budget authority within approved vendor spend',
    typicalBudgetRange: '$20,000 - $150,000',
    influenceChain: { reportsTo: 'CFO / Operations', needsApprovalFrom: ['Finance', 'Legal'], influencedBy: ['Project teams', 'End users'] },
    tonePreference: 'Professional and contract-focused',
    communicationStyle: 'Process-oriented and documentation-heavy',
    attentionSpan: 'Medium—values clarity and predictability',
    technicalTriggers: ['SLA documentation', 'Pricing structure', 'Quality guarantees'],
    emotionalTriggers: ['Vendor reliability', 'Budget protection', 'Process efficiency'],
    vetoPower: true,
    defaultRiskLevel: 'medium',
    disqualifiers: ['No formal contracts', 'Variable pricing only'],
    buyingModeStrategies: {
      firefighter: 'Lead with reliability: "Emergency support with guaranteed delivery—no excuses, just results."',
      optimizer: 'Lead with predictability: "Fixed pricing and guaranteed turnarounds eliminate budget surprises."',
      innovator: 'Lead with partnership: "Master service agreement for portfolio-wide coverage with volume benefits."'
    },
    requiredAssets: ['pricing_matrix', 'sla_template', 'vendor_references'],
    proposalSections: ['pricing', 'sla_terms', 'references', 'contract_terms'],
  },
  {
    code: 'BP-PROPTECH',
    name: 'The PropTech Innovator',
    icon: 'Rocket',
    roleTitle: 'PropTech / Startup Founder',
    roleVariants: ['CEO', 'CTO', 'Product Lead', 'Innovation Director'],
    organizationType: 'PropTech Startup / Innovation Lab',
    description: 'Technology innovator seeking reality capture for digital products or building analytics. Values API access, data quality, and scalability.',
    coreValues: ['Innovation', 'Scalability', 'Data Quality', 'Speed to Market'],
    primaryPain: 'Need high-quality building data to power digital products',
    secondaryPain: 'Finding reliable scanning partners who understand tech integration',
    hiddenFear: 'Building product on unreliable or inconsistent data source',
    purchaseTriggers: ['Product development', 'Pilot projects', 'Portfolio rollout', 'Data partnerships'],
    valueDriver: 'Power your product with verified building data at scale',
    valueHook: 'Fuel your innovation with reality-verified building data. Quality at scale.',
    exactLanguage: ['data pipeline', 'API integration', 'scalable capture', 'consistent quality'],
    avoidWords: ['traditional', 'standard process', 'typical approach'],
    decisionCriteria: ['Data consistency', 'Integration capability', 'Scalability', 'Partnership flexibility'],
    dealbreakers: ['Inconsistent data quality', 'No API access', 'Rigid processes'],
    projectPhases: ['Proof of concept', 'Pilot', 'Scale deployment', 'Ongoing partnership'],
    budgetAuthority: 'Full authority within venture budget',
    typicalBudgetRange: '$20,000 - $200,000+ (portfolio)',
    influenceChain: { reportsTo: 'Board/Investors', needsApprovalFrom: [], influencedBy: ['Technical team', 'Product team'] },
    tonePreference: 'Innovative and partnership-oriented',
    communicationStyle: 'Collaborative and visionary',
    attentionSpan: 'Long for strategic, short for tactical',
    technicalTriggers: ['API documentation', 'Data formats', 'Integration examples'],
    emotionalTriggers: ['Innovation partnership', 'Competitive advantage', 'Market leadership'],
    vetoPower: true,
    defaultRiskLevel: 'medium',
    disqualifiers: ['One-off projects only', 'Traditional requirements'],
    buyingModeStrategies: {
      firefighter: 'Lead with capability: "Pilot capture to prove concept—data ready for integration in 2 weeks."',
      optimizer: 'Lead with scale: "Proven methodology for consistent data across portfolio capture."',
      innovator: 'Lead with partnership: "Co-develop data specifications for your unique product requirements."'
    },
    requiredAssets: ['technical_integration_guide', 'api_documentation', 'partnership_case_study'],
    proposalSections: ['partnership_overview', 'technical_specifications', 'scalability_plan', 'integration'],
  },
  {
    code: 'BP-INST',
    name: 'The Institutional Owner',
    icon: 'Landmark',
    roleTitle: 'Corporate Real Estate / REIT',
    roleVariants: ['VP Real Estate', 'Director of Capital Projects', 'Asset Portfolio Manager', 'Corporate Facilities'],
    organizationType: 'REIT / Corporate Real Estate / Institutional',
    description: 'Enterprise decision-maker managing large portfolios. Values standardization, vendor reliability, and enterprise-grade documentation.',
    coreValues: ['Portfolio Standardization', 'Vendor Reliability', 'Risk Management', 'Reporting Consistency'],
    primaryPain: 'Inconsistent documentation across portfolio complicates planning and reporting',
    secondaryPain: 'Multiple vendors creating quality variance',
    hiddenFear: 'Asset valuation issues from inaccurate documentation',
    purchaseTriggers: ['Portfolio-wide initiative', 'Standardization project', 'M&A due diligence', 'ESG reporting'],
    valueDriver: 'Standardize portfolio documentation with enterprise-grade capture',
    valueHook: 'One standard. Every building. Complete portfolio visibility.',
    exactLanguage: ['portfolio standardization', 'enterprise documentation', 'consistent methodology', 'reporting-ready'],
    avoidWords: ['custom', 'one-off', 'project-by-project'],
    decisionCriteria: ['National coverage', 'Standardized deliverables', 'Enterprise pricing', 'Reporting integration'],
    dealbreakers: ['Limited geographic coverage', 'Inconsistent quality', 'No enterprise agreements'],
    projectPhases: ['Portfolio assessment', 'Pilot buildings', 'Rollout phases', 'Ongoing program'],
    budgetAuthority: 'Large program authority, board approval for enterprise agreements',
    typicalBudgetRange: '$100,000 - $1,000,000+ (portfolio)',
    influenceChain: { reportsTo: 'C-Suite / Board', needsApprovalFrom: ['CFO', 'Legal', 'Procurement'], influencedBy: ['Regional teams', 'Consultants'] },
    tonePreference: 'Enterprise/institutional—formal and comprehensive',
    communicationStyle: 'Strategic and procurement-oriented',
    attentionSpan: 'Long for strategic value, short for tactical details',
    technicalTriggers: ['Quality assurance program', 'National coverage map', 'Enterprise SLA'],
    emotionalTriggers: ['Portfolio control', 'Reporting confidence', 'Competitive positioning'],
    vetoPower: true,
    defaultRiskLevel: 'low',
    disqualifiers: ['Single building projects', 'No enterprise capability'],
    buyingModeStrategies: {
      firefighter: 'Lead with capacity: "National team can mobilize across your portfolio simultaneously."',
      optimizer: 'Lead with enterprise value: "Portfolio pricing delivers 30% savings vs. project-by-project."',
      innovator: 'Lead with vision: "Create the industry\'s first fully documented institutional portfolio."'
    },
    requiredAssets: ['enterprise_proposal_template', 'portfolio_case_study', 'coverage_map', 'sla_documentation'],
    proposalSections: ['executive_summary', 'enterprise_value', 'portfolio_approach', 'governance', 'investment'],
  },
];

export async function seedPersonas() {
  console.log('Seeding buyer personas...');
  
  for (const persona of PERSONA_SEED_DATA) {
    try {
      const existing = await db
        .select()
        .from(buyerPersonas)
        .where((await import('drizzle-orm')).eq(buyerPersonas.code, persona.code))
        .limit(1);
      
      if (existing.length > 0) {
        await db
          .update(buyerPersonas)
          .set({
            ...persona,
            updatedAt: new Date(),
          })
          .where((await import('drizzle-orm')).eq(buyerPersonas.code, persona.code));
        console.log(`  Updated persona: ${persona.code} - ${persona.name}`);
      } else {
        await db.insert(buyerPersonas).values({
          ...persona,
          tonePreference: persona.tonePreference,
          isActive: true,
        });
        console.log(`  Created persona: ${persona.code} - ${persona.name}`);
      }
    } catch (error) {
      console.error(`  Error seeding ${persona.code}:`, error);
    }
  }
  
  console.log('Buyer personas seeded successfully.');
}
