export const SERVER_CONSTANTS = {
  TOKEN_EXPIRY_DAYS: 7,
  PDF_MAX_CHARS: 15000,
  MAX_RETRIES: 3,
  REQUEST_TIMEOUT_MS: 30000,
  SESSION_COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000,
  RATE_LIMIT_WINDOW_MS: 1 * 60 * 1000, // 1 minute window
  RATE_LIMIT_MAX_REQUESTS: 500,
  AUTH_RATE_LIMIT_MAX_REQUESTS: 100,
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: 10000,
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const GOOGLE_CHAT_DEFAULT_MEMBERS = (
  process.env.GOOGLE_CHAT_DEFAULT_MEMBERS || 
  "ceo@scan2plan.dev,accounting@scan2plan.dev,production@scan2plan.dev"
).split(",").filter(Boolean);
